name: Kotlin
version: @VERSION@
main: dev.hawu.plugins.kotlin.bukkit.BukkitEntrypoint
description: Introduces Kotlin's standard, serialization and coroutines library to Bukkit.
load: STARTUP
website: https://kotlinlang.org
author: JetBrains